from .prompts import (
    UNIFIED_AGENT_PROMPT,
    ORCHESTRATOR_PROMPT,  # Keep for reference
    SALES_AGENT_PROMPT,
    SUPPORT_AGENT_PROMPT,
    OPERATIONS_AGENT_PROMPT,
    TECHNICAL_AGENT_PROMPT
)

__all__ = [
    'UNIFIED_AGENT_PROMPT',
    'ORCHESTRATOR_PROMPT',
    'SALES_AGENT_PROMPT',
    'SUPPORT_AGENT_PROMPT',
    'OPERATIONS_AGENT_PROMPT',
    'TECHNICAL_AGENT_PROMPT'
]
